# Dependencies
markdown:         kramdown
redcarpet:
  extensions:     [strikethrough,smart,with_toc_data,tables]
highlighter:      rouge

# Permalinks
permalink:        /posts/:title/

# User Configuration
title:            Deepan's Blog
tagline:          'Learn To Fail!!'
description:      'Love to share! and mentor!! Love to have one!'
url:              http://deepanman.com
baseurl:          '/'
paginate:         5
excerpt_separator: '<br>'
gems:
- jekyll-mentions
- jemoji
- jekyll-redirect-from
- jekyll-sitemap
- jekyll-paginate

# Author Info
author:
  name:           'Deepan Kumar Manivannan'
  url:            https://twitter.com/umail2deep

# Social Integration
social:
  twitter:        umail2deep
  disqus:         www-deepanman-com
  addthis_pubid:  ra-57c2814f725f1d1c

# Google Analytics Configuration
# Proxy response must be in JSON and should have the fields - ga:pagePath, ga:pageview
google_analytics:
  tracking_id:      
  super_proxy_url:  

# Github
github:
  repo:           https://github.com/1deepan1/1deepan1.github.io
  feedback:       https://github.com/1deepan1/feedback/issues/new

# Version Info
version:          1.0.0